services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"

  comment-worker:
    build:
      context: ./worker/comment_worker
      dockerfile: Dockerfile
    container_name: comment-worker
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
      QUEUE_NAME: youtube.comment.link.q
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB: YouTube_feedback_intelligence
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    #env_file:
    #  - .env

volumes:
  mongodb_data:
