spring.application.name=YouTube Feedback Intelligence

spring.data.mongodb.uri= mongodb://localhost:27017/youtube_feedback_intelligence
spring.data.mongodb.database= YouTube_feedback_intelligence


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbit.exchange=youtube.exchange
app.rabbit.routing.link=youtube.comment.link
app.rabbit.queue.link=youtube.comment.link.q